# Generated by Django 3.2.5 on 2021-08-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=' ', editable=False, max_length=200),
        ),
    ]
